### ISSUE TITLE
Firefox - Login menu go out of windows

### ISSUE THREAD

**Issue by AntoineLemaire** [electronoob/agarmods#122] opened 2015-06-20 10:39 UTC
Windows 7
Firefox 38.0.5
Greasemonkey 3.2
Agarmods 1.9

Screen :
![sans titre-1](https://cloud.githubusercontent.com/assets/2025537/8266939/29d46fdc-1749-11e5-82a9-fb5060fe70f2.jpg)

**Comment by Mevin1** [comment] 2015-06-20 13:44
Caused by agar.io update, fixed in 1.9.5

**Closed** 2015-07-08 07:28 UTC
